name: build-posts
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
jobs:
  Docs:
    name: build-posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        uses: Dylan-Prins/actions-mkdocs@main
        with:
          requirements: "mkdocs.txt"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
