name: 🚀 hugo publish

on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update theme
      run: git submodule update --init --recursive

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    # - run: |
    #     npm install
    #     npm i -g postcss-cli
    #     npm i && HUGO_ENVIRONMENT=production hugo --gc

    - name: Build
      run: hugo  --enableGitInfo --minify

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     publish_branch: gh-pages
    #     publish_dir: ./public
    #     github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: public
        fqdn: anotherdevops.blog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}