name: 🚀 hugo publish

on:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update theme
      run: git submodule update --init --recursive

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build
      run: hugo  --enableGitInfo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: main
        publish_dir: ./public
        github_token: ${{ secrets.GITHUB_TOKEN }}